/* Automatically generated by wasm2c */
#ifndef RUNTIME_H_GENERATED_
#define RUNTIME_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;
struct w2c_wasi__snapshot__preview1;

typedef struct w2c_runtime {
  struct w2c_env* w2c_env_instance;
  struct w2c_wasi__snapshot__preview1* w2c_wasi__snapshot__preview1_instance;
  u32 w2c_g0;
  u32 w2c_g1;
  u32 w2c_g2;
  u32 w2c_g3;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_0x5F_indirect_function_table;
} w2c_runtime;

void wasm2c_runtime_instantiate(w2c_runtime*, struct w2c_env*, struct w2c_wasi__snapshot__preview1*);
void wasm2c_runtime_free(w2c_runtime*);
wasm_rt_func_type_t wasm2c_runtime_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' 'emscripten_memcpy_js' */
void w2c_env_emscripten_memcpy_js(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'emscripten_resize_heap' */
u32 w2c_env_emscripten_resize_heap(struct w2c_env*, u32);

/* import: 'wasi_snapshot_preview1' 'fd_close' */
u32 w2c_wasi__snapshot__preview1_fd_close(struct w2c_wasi__snapshot__preview1*, u32);

/* import: 'wasi_snapshot_preview1' 'fd_seek' */
u32 w2c_wasi__snapshot__preview1_fd_seek(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_write' */
u32 w2c_wasi__snapshot__preview1_fd_write(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_runtime_memory(w2c_runtime* instance);

/* export: '__wasm_call_ctors' */
void w2c_runtime_0x5F_wasm_call_ctors(w2c_runtime*);

/* export: 'create_buff' */
u32 w2c_runtime_create_buff(w2c_runtime*, u32);

/* export: 'malloc' */
u32 w2c_runtime_malloc(w2c_runtime*, u32);

/* export: 'stp' */
u32 w2c_runtime_stp(w2c_runtime*, u32);

/* export: 'sbug' */
u32 w2c_runtime_sbug(w2c_runtime*, u32, u32);

/* export: 'de3' */
u32 w2c_runtime_de3(w2c_runtime*, u32, u32, u32, u32, u32, u32);

/* export: 'getoutputPtr' */
u32 w2c_runtime_getoutputPtr(w2c_runtime*);

/* export: 'free_buff' */
void w2c_runtime_free_buff(w2c_runtime*, u32);

/* export: 'main' */
u32 w2c_runtime_main(w2c_runtime*, u32, u32);

/* export: '__indirect_function_table' */
wasm_rt_funcref_table_t* w2c_runtime_0x5F_indirect_function_table(w2c_runtime* instance);

/* export: 'ntohs' */
u32 w2c_runtime_ntohs(w2c_runtime*, u32);

/* export: 'fflush' */
u32 w2c_runtime_fflush(w2c_runtime*, u32);

/* export: 'htonl' */
u32 w2c_runtime_htonl(w2c_runtime*, u32);

/* export: 'htons' */
u32 w2c_runtime_htons(w2c_runtime*, u32);

/* export: 'emscripten_builtin_memalign' */
u32 w2c_runtime_emscripten_builtin_memalign(w2c_runtime*, u32, u32);

/* export: 'setTempRet0' */
void w2c_runtime_setTempRet0(w2c_runtime*, u32);

/* export: 'emscripten_stack_init' */
void w2c_runtime_emscripten_stack_init(w2c_runtime*);

/* export: 'emscripten_stack_get_free' */
u32 w2c_runtime_emscripten_stack_get_free(w2c_runtime*);

/* export: 'emscripten_stack_get_base' */
u32 w2c_runtime_emscripten_stack_get_base(w2c_runtime*);

/* export: 'emscripten_stack_get_end' */
u32 w2c_runtime_emscripten_stack_get_end(w2c_runtime*);

/* export: 'stackSave' */
u32 w2c_runtime_stackSave(w2c_runtime*);

/* export: 'stackRestore' */
void w2c_runtime_stackRestore(w2c_runtime*, u32);

/* export: 'stackAlloc' */
u32 w2c_runtime_stackAlloc(w2c_runtime*, u32);

/* export: 'emscripten_stack_get_current' */
u32 w2c_runtime_emscripten_stack_get_current(w2c_runtime*);

/* export: 'dynCall_jiji' */
u32 w2c_runtime_dynCall_jiji(w2c_runtime*, u32, u32, u32, u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* RUNTIME_H_GENERATED_ */
